---
title: "Lab 05"
author: "Moushreeta Debroy(22122132)"
date: "2022-11-22"
output:
  word_document: default
  html_document: default
---

```{r}
library(readxl)
Breast_Cancer <- read_excel("C:/Users/PRASANTA/Downloads/Breast_Cancer.xls")
View(Breast_Cancer)

```
```{r}
colnames(Breast_Cancer)
```
```{r}
head(Breast_Cancer)
```

```{r}
library('EnvStats')
```
```{r}
x<-Breast_Cancer$`Tumor Size`
x
```
```{r}
var(x)
```
H0:var_Tumor size=450
H1:var_Tumor Size!=450


```{r}
varTest(x,alternative = "two.sided",sigma.squared = 450,conf.level = 0.95)

```
Conclusion:Here P value is  0.6978332 which is greater than alpha=0.05,so here we accept the null hypothesis.


```{r}
White<-subset(Breast_Cancer,Race=='White')

```

```{r}
Black<-subset(Breast_Cancer,Race=='Black')

```

```{r}
y<-Breast_Cancer$Race
y
```
```{r}
var(White$`Tumor Size`)
```

```{r}
var(Black$`Tumor Size`)

```
v1=tumor size of White(race)
v2=tumor size of Black(race)

H0:v1=v2
H1:v1!=v2


```{r}
var.test(White$`Tumor Size`,Black$`Tumor Size`,alternative = 'two.sided',conf.level = 0.95)
```
Conclusion: Here p value is less than alpha.so we reject the  null hypothesis.Therefore tumor size of White(race) is not equal to tumor size of Black(race).